namespace DWinverNS
{
    public partial class CaD
    {
        // Designer-generated InitializeComponent
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CaD));
            SuspendLayout();
            // 
            // CaD
            // 
            ClientSize = new Size(184, 11);
            if (ArgsMgr.debugMode)
            {
                Enabled = true;
                ShowIcon = true;
                ShowInTaskbar = true;
            }
            FormBorderStyle = FormBorderStyle.FixedToolWindow;
            Icon = (Icon)resources.GetObject("$this.Icon");
            MaximizeBox = false;
            Name = "CaD";
            Text = ".exe OK PSScript? IDK";
            UseWaitCursor = true;
            ResumeLayout(false);
        }

        // Dispose method (generated by designer)
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private System.ComponentModel.IContainer components = null;
    }
}