name: Build Windows EXE

# Trigger build on push to main branch or manual trigger
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout your code
    - uses: actions/checkout@v3

    # Step 2: Build your project
    # For a batch script or simple project, just copy files
    - name: Prepare EXE
      run: |
        mkdir published
        copy *.bat published\

    # If you have a C# / .NET project, uncomment these lines:
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: '7.0.x'
    #
    # - name: Build project
    #   run: dotnet build YourProject.sln -c Release
    #
    # - name: Publish EXE
    #   run: dotnet publish YourProject.sln -c Release -o published

    # Step 3: Upload build artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dwinver-build
        path: published/