name: Build .NET Core Desktop EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Match your project version

    - name: Restore dependencies
      run: dotnet restore DWinver.sln

    - name: Build project
      run: dotnet build DWinver.sln -c Release --no-restore

    - name: Publish EXE x86
      run: dotnet publish DWinver.sln -c Release -r win-x86 -o published --self-contained true -o published

    - name: Publish EXE x64
      run: dotnet publish DWinver.sln -c Release -r win-x64 -o published --self-contained true -o published

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dwinver-build
        path: published/
